### ISSUE TITLE
Error while importing account

### ISSUE THREAD

**Issue by dariocast** [RootSoft/flutter-algorand-wallet#2]
```
E/flutter (31545): [ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: Unhandled error type 'Null' is not a subtype of type 'int' in type cast occurred in Instance of 'WalletBloc'.
E/flutter (31545): #0      List.length= (dart:core-patch/growable_array.dart:222:12)
E/flutter (31545): #1      _IntListMixin.+ (dart:typed_data-patch/typed_data_patch.dart:156:9)
E/flutter (31545): #2      Address.encodeAddress
package:algorand_dart/…/addresses/address_model.dart:53
E/flutter (31545): #3      new Address
package:algorand_dart/…/addresses/address_model.dart:24
E/flutter (31545): #4      new Account._create
package:algorand_dart/…/accounts/account_model.dart:17
E/flutter (31545): #5      Account.fromSeed
package:algorand_dart/…/accounts/account_model.dart:48
E/flutter (31545): <asynchronous suspension>
E/flutter (31545): #6      Algorand.restoreAccount
package:algorand_dart/src/algorand.dart:106
E/flutter (31545): <asynchronous suspension>
E/flutter (31545): #7      AccountRepository.importAccount
package:flutter_algorand_wallet/repositories/account_repository.dart:54
E/flutter (31545): <asynchronous suspension>
E/flutter (31545): #8      WalletBloc.mapEventToState
package:flutter_algorand_wallet/…/bloc/wallet_bloc.dart:33
E/flutter (31545): <asynchronous suspension>
```

Passphrase is correct and on testnet

**Comment by RootSoft** [comment]
See https://github.com/RootSoft/algorand-dart/issues/4#issuecomment-864578665
